version: "3.9"

services:
  php-fpm:
    build:
      args:
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    command: sh -c "cd /home/dockeruser && chown $USER_ID:$GROUP_ID magento && php-fpm"
    container_name: docker-magento_php-fpm
    networks:
      - internal
    user: $USER_ID:$GROUP_ID
    volumes:
      - ./magento:/home/dockeruser/magento
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/.composer:/home/dockeruser/.composer

  nginx:
    build:
      args:
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command: sh -c "cd /home/dockeruser && chown $USER_ID:$GROUP_ID magento && nginx -g 'daemon off;'"
    container_name: docker-magento_nginx
    depends_on:
      - php-fpm
    networks:
      - external
      - internal
    ports:
      - 80:8080
    user: $USER_ID:$GROUP_ID
    volumes:
      - ./magento:/home/dockeruser/magento
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: docker-magento_mysql
    environment:
      MYSQL_DATABASE: "magento"
      MYSQL_PASSWORD: "magento"
      MYSQL_ROOT_PASSWORD: "magento"
      MYSQL_USER: "magento"
    networks:
      - internal
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql

  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elasticsearch/Dockerfile
    container_name: docker-magento_elasticsearch
    environment:
      ELASTIC_PASSWORD: changeme
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
    networks:
      - internal
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    build:
      context: .
      dockerfile: ./docker/logstash/Dockerfile
    container_name: docker-magento_logstash
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - internal
    volumes:
      - ./docker/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline

  filebeat:
    build:
      context: .
      dockerfile: ./docker/filebeat/Dockerfile
    container_name: docker-magento_filebeat
    depends_on:
      - elasticsearch
    networks:
      - internal
    volumes:
      - ./docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - nginx_logs:/var/log/nginx
      - ./magento/var/log:/var/log/magento
      - ./magento/var/report:/var/report/magento

  kibana:
    build:
      context: .
      dockerfile: ./docker/kibana/Dockerfile
    container_name: docker-magento_kibana
    depends_on:
      - elasticsearch
    networks:
      - internal
    platform: linux/amd64
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
    container_name: docker-magento_rabbitmq
    networks:
      - internal

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    container_name: docker-magento_redis
    networks:
      - internal

  redis-admin:
    build:
      context: .
      dockerfile: ./docker/redis-admin/Dockerfile
    container_name: docker-magento_redis-admin
    environment:
      REDIS_1_HOST: "redis"
    networks:
      - internal

  adminer:
    build:
      context: .
      dockerfile: ./docker/adminer/Dockerfile
    container_name: docker-magento_adminer
    depends_on:
      - mysql
    networks:
      - internal

  mailhog:
    build:
      context: .
      dockerfile: ./docker/mailhog/Dockerfile
    networks:
      - internal

networks:
  internal:
  external:

volumes:
  elasticsearch:
  mysql:
  nginx_logs:
  magento_logs:
  magento_reports:
