version: "3.9"

services:
  php-fpm:
    build:
      args:
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: .
      dockerfile: ./images/php-fpm/Dockerfile
    command: sh -c "cd /home/dockeruser && chown $USER_ID:$GROUP_ID magento && php-fpm"
    container_name: docker-magento_php-fpm
    depends_on:
      - mysql
    networks:
      - external
      - internal
    volumes:
      - ./magento:/home/dockeruser/magento
      - ./images/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./images/php-fpm/.composer:/home/dockeruser/.composer

  node:
    build:
      args:
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: .
      dockerfile: ./images/node/Dockerfile
    command: sh -c "cd /home/node && chown $USER_ID:$GROUP_ID frontend && tail -f /dev/null"
    container_name: docker-magento_node
    environment:
      MAGENTO_GRAPHQL: "http://nginx:8080/graphql"
    networks:
      - external
      - internal
    volumes:
      - ./frontend:/home/node/frontend

  nginx:
    build:
      args:
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: .
      dockerfile: ./images/nginx/Dockerfile
    command: sh -c "cd /home/dockeruser && chown $USER_ID:$GROUP_ID magento && nginx -g 'daemon off;'"
    container_name: docker-magento_nginx
    depends_on:
      - php-fpm
      - node
      - adminer
      - kibana
      - rabbitmq
      - redis-admin
    networks:
      - external
    ports:
      - 80:8080
    volumes:
      - ./magento:/home/dockeruser/magento
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx

  mysql:
    build:
      context: .
      dockerfile: ./images/mysql/Dockerfile
    container_name: docker-magento_mysql
    environment:
      MYSQL_DATABASE: "magento"
      MYSQL_PASSWORD: "magento"
      MYSQL_ROOT_PASSWORD: "magento"
      MYSQL_USER: "magento"
    networks:
      - internal
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    build:
      context: .
      dockerfile: ./images/adminer/Dockerfile
    container_name: docker-magento_adminer
    depends_on:
      - mysql
    networks:
      - external
      - internal

  elasticsearch:
    build:
      args:
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: .
      dockerfile: ./images/elasticsearch/Dockerfile
    container_name: docker-magento_elasticsearch
    environment:
      ELASTIC_PASSWORD: changeme
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
    networks:
      - internal
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./images/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    build:
      context: .
      dockerfile: ./images/logstash/Dockerfile
    container_name: docker-magento_logstash
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - internal
    volumes:
      - ./images/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./images/logstash/pipeline:/usr/share/logstash/pipeline

  filebeat:
    build:
      context: .
      dockerfile: ./images/filebeat/Dockerfile
    container_name: docker-magento_filebeat
    depends_on:
      - logstash
    networks:
      - internal
    volumes:
      - ./images/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - nginx_logs:/var/log/nginx
      - ./magento/var/log:/var/log/magento
      - ./magento/var/report:/var/report/magento

  kibana:
    build:
      context: .
      dockerfile: ./images/kibana/Dockerfile
    container_name: docker-magento_kibana
    depends_on:
      - elasticsearch
    networks:
      - external
      - internal
    platform: linux/amd64
    volumes:
      - ./images/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  rabbitmq:
    build:
      context: .
      dockerfile: ./images/rabbitmq/Dockerfile
    container_name: docker-magento_rabbitmq
    networks:
      - external
      - internal

  redis:
    build:
      context: .
      dockerfile: ./images/redis/Dockerfile
    container_name: docker-magento_redis
    networks:
      - internal

  redis-admin:
    build:
      context: .
      dockerfile: ./images/redis-admin/Dockerfile
    container_name: docker-magento_redis-admin
    depends_on:
      - redis
    environment:
      REDIS_1_HOST: "redis"
    networks:
      - external
      - internal

  mailhog:
    build:
      context: .
      dockerfile: ./images/mailhog/Dockerfile
    container_name: docker-magento_mailhog
    networks:
      - internal

networks:
  internal:
  external:

volumes:
  elasticsearch:
  mysql:
  nginx_logs:
